---
title: "modeling"
author: "Layla Brassington"
date: "2026-07-24"
output: html_document
---

```{r}
library(readr)
library(limma)
library(EMMREML)
library(edgeR)
library(ggplot2)
library(stringr)
library(dplyr)
library(magrittr)
library(tidyverse)
library(broom)
library(purrr)
```


### Immune biomarker statistical analyses  ---

average repeated samples
```{r}
cols_of_interest <- c("IL-8", "IL-6", "TNF-α", "CRP", "IL-13", "LBP", "Leptin","IL-2", "IL-1β", "IL-4", "IFN-γ", "IL-10", "IL-12")

df <- biomarkers %>% group_by(Sample.ID) %>%
  summarise(across(all_of(cols_of_interest), ~ mean(.x, na.rm = TRUE)), .groups = "drop")
```

standardize data
```{r}
# 1. Log-transform 
df[cols_of_interest] <- log2(df[cols_of_interest])

# 2. Z-score scale (center and scale each column)
df[cols_of_interest] <- scale(df[cols_of_interest])
```

fit linear model for each cytokine
```{r}
safe_model <- safely(function(colname) {
  formula_str <- paste0(
    colname, " ~ urb_scale + early_scale + age_scale + sex_medical + Plate"
  )
  f <- as.formula(formula_str)
  model <- lm(f, data = df)

  # Get tidy model summary and number of observations
  list(
    tidy = broom::tidy(model),    # this includes Estimate, Std. Error, t value, Pr(>|t|)
    n = nobs(model)
  )
})

model_results <- map(set_names(cols_of_interest, cols_of_interest), safe_model)
```



### Differential expression analyses  ---

```{r}
meta <- readRDS("/filepath/meta_data.rds")
exp <- readRDS("/filepath/exp.rds")
K <- readRDS("/filepath/K.rds")
```

make sure everything is in the same order
```{r}
identical(meta$sample_name,colnames(exp))
identical(meta$sample_name,colnames(K))
identical(colnames(exp),colnames(K))
```

```{r}
#ensure group is a factor 
meta$ancestry_groups = as.factor(meta$ancestry_groups)

modSv = model.matrix(~urb_scale + early_scale + age_scale + sex_medical + ancestry_groups, data=meta)

Z <- matrix(0, nrow = length(rownames(K)), ncol = length(colnames(K)))
rownames(Z) <- rownames(K)
colnames(Z) <- colnames(K)

for (i in seq_along(rownames(Z))) {
  match_idx <- match(rownames(Z)[i], meta$sample_name)
  if (!is.na(match_idx)) {
    Z[i, match_idx] <- 1
  }
}

#Declare object res_full to store in it the model results: beta coefficients, standard deviations and p values
res_full = matrix(NA, nrow=nrow(exp), ncol=3 * ncol(modSv))
colnames(res_full) = c(
  paste0("beta_", colnames(modSv)),
  paste0("sdev_", colnames(modSv)),
  paste0("p_value_", colnames(modSv))
)
res_full = as.data.frame(res_full)
rownames(res_full)=rownames(exp)

#run the model and store results (need to run in console)
for(i in 1:nrow(exp))
{
  emma=emmreml(y=exp[i,],X=modSv,Z=as.matrix(Z),K=as.matrix(K),varbetahat=T,varuhat=T,PEVuhat=T,test=T)
  res_full[i,]=t(c(emma$betahat,emma$varbetahat,emma$pvalbeta[,"none"]))
  print(i)
}
```

### Elastic net classifier  ---


training data
```{r}
stable_idx <- meta %>% filter(lifestyle_bins %in% c("always_nonindustrial", "always_industrialized")) %>% dplyr::select(sample_name)
X <- exp[, stable_idx$sample_name]
X <- t(X) 
y <- factor(meta$lifestyle_bins[match(rownames(X), meta$sample_name)], levels = c("always_nonindustrial", "always_industrialized"))
y_bin <- ifelse(y == "always_industrialized", 1, 0)
```

```{r}
pred <- rep(NA, length(y_bin))

for (i in seq_along(y_bin)) {

  X_train <- X[-i, ]
  y_train <- y_bin[-i]

  X_test <- X[i, , drop = FALSE]

  cvfit <- cv.glmnet(x = X_train, y = y_train, family = "binomial", alpha = 1, nfolds = 50)

  pred[i] <- predict(cvfit, newx = X_test, s = "lambda.min", type = "response")
  
  print(i)
}
```

look at how well it predicts with the leave one out 
```{r}
roc_obj <- roc(y_bin, pred)
auc(roc_obj)
```

```{r}
final_fit <- cv.glmnet(x = X, y = y_bin, family = "binomial", alpha = 1, nfolds = 50)

switch_idx = meta %>% filter(lifestyle_bins %in% c("nonindustrial_to_industrialized", "industrialized_to_nonindustrial")) %>% dplyr::select(sample_name)
X_switch <- t(exp[, switch_idx$sample_name])   # transpose: samples × genes

# Predict urbanicity probability for switchers
switch_scores <- predict(final_fit, newx = X_switch, s = "lambda.min", type = "response")
```
